# Generated by Django 6.0.1 on 2026-01-31 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='absentDays',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='presentDays',
            field=models.IntegerField(default=0),
        ),
    ]
